import type { HistorySpec } from './history.ts'

/**
 * The planted sources and the one scripted history the PR goldens are recorded
 * against. They live here rather than inside the test because the goldens are
 * regenerated by a script that cannot import a vitest module — and a golden
 * whose fixture is defined twice is a golden that drifts.
 */

/** A function whose `const` is reassigned — oxlint's `no-const-assign`. */
export const CONST_ASSIGN = `export function bump() {
  const limit = 1
  limit = 2
  return limit
}
`

/** The same function, correct: no finding. */
export const CLEAN = `export function bump() {
  let limit = 1
  limit = 2
  return limit
}
`

/** Statements after an unconditional `return` — oxlint's `no-unreachable`. */
export const UNREACHABLE = `export function loop() {
  return 1
  return 2
}
`

/** Duplicate object keys — oxlint's `no-dupe-keys`. */
export const DUPE_KEYS = `export function dupe() {
  return { x: 1, x: 2 }
}
`

/** One history with all three outcomes in it: resolved, renamed, and new. */
export const GOLDEN_HISTORY: HistorySpec = {
  base: {
    'src/fixed.js': CONST_ASSIGN,
    'src/moved.js': DUPE_KEYS,
    'src/clean.js': 'export const value = 1\n',
  },
  head: [
    { write: 'src/fixed.js', content: CLEAN },
    { rename: 'src/moved.js', to: 'src/renamed.js' },
    { write: 'src/clean.js', content: UNREACHABLE },
  ],
}
