import type { HistorySpec } from './history.ts'

/**
 * The planted sources and the scripted histories the PR tests run on. They live
 * here rather than inside the tests because the goldens are regenerated by a
 * script that cannot import a vitest module — and a golden whose fixture is
 * defined twice is a golden that drifts.
 */

/** A function whose `const` is reassigned — oxlint's `no-const-assign`. */
export const CONST_ASSIGN = `export function bump() {
  const limit = 1
  limit = 2
  return limit
}
`

/** The same function, correct: no finding. */
export const CLEAN = `export function bump() {
  let limit = 1
  limit = 2
  return limit
}
`

/** Statements after an unconditional `return` — oxlint's `no-unreachable`. */
const UNREACHABLE = `export function loop() {
  return 1
  return 2
}
`

/** Duplicate object keys — oxlint's `no-dupe-keys`. */
const DUPE_KEYS = `export function dupe() {
  return { x: 1, x: 2 }
}
`

/** A file with no finding in it, so a package stays a package after a move. */
const CLEAN_VALUE = 'export const value = 1\n'

/**
 * A second `const` reassignment, deliberately not a copy of {@link CONST_ASSIGN}:
 * git pairs a deleted file with an identical added one as a rename, and a
 * fixture that deletes one package and adds another must not have the two read
 * as the same file moving.
 */
const SCALE_CONST_ASSIGN = `export function scale() {
  const factor = 2
  factor = 3
  return factor
}
`

/** A package manifest that declares nothing: the toolchain is the root's. */
function packageJson(name: string): string {
  return `${JSON.stringify({ name, version: '0.0.0', private: true }, null, 2)}\n`
}

/**
 * The root oxlint config every package inherits — the one artifact a change can
 * edit at the root and have it land in a package it never touched.
 */
function oxlintConfig(noUnreachable: 'off' | 'error'): string {
  return `${JSON.stringify({ rules: { 'no-unreachable': noUnreachable } }, null, 2)}\n`
}

/**
 * `mono-pr`: a workspace whose head commit does every project-level thing a PR
 * can do at once (spec §4's PR delta over projects).
 *
 * - the **root config** turns a rule on, which moves `packages/steady` — a
 *   package the diff never touches
 * - a file is `git mv`-ed from `packages/mover` to `packages/target`, so one
 *   finding changes project without changing identity
 * - `packages/dropped` is deleted and `packages/added` appears, which are the
 *   two project churn states
 *
 * `packages/mover` keeps a second source file so that losing the moved one
 * leaves it a project rather than turning it into churn of its own.
 */
export const MONO_PR_HISTORY: HistorySpec = {
  base: {
    'package.json': `${JSON.stringify({ name: 'mono', private: true, workspaces: ['packages/*'] }, null, 2)}\n`,
    '.oxlintrc.json': oxlintConfig('off'),
    'packages/steady/package.json': packageJson('steady'),
    'packages/steady/src/index.js': UNREACHABLE,
    'packages/mover/package.json': packageJson('mover'),
    'packages/mover/src/clone.js': DUPE_KEYS,
    'packages/mover/src/keep.js': CLEAN_VALUE,
    'packages/target/package.json': packageJson('target'),
    'packages/target/src/index.js': CLEAN_VALUE,
    'packages/dropped/package.json': packageJson('dropped'),
    'packages/dropped/src/index.js': CONST_ASSIGN,
  },
  head: [
    { write: '.oxlintrc.json', content: oxlintConfig('error') },
    { rename: 'packages/mover/src/clone.js', to: 'packages/target/src/clone.js' },
    { remove: 'packages/dropped/src/index.js' },
    { remove: 'packages/dropped/package.json' },
    { write: 'packages/added/package.json', content: packageJson('added') },
    { write: 'packages/added/src/index.js', content: SCALE_CONST_ASSIGN },
  ],
}

/** One history with all three outcomes in it: resolved, renamed, and new. */
export const GOLDEN_HISTORY: HistorySpec = {
  base: {
    'src/fixed.js': CONST_ASSIGN,
    'src/moved.js': DUPE_KEYS,
    'src/clean.js': 'export const value = 1\n',
  },
  head: [
    { write: 'src/fixed.js', content: CLEAN },
    { rename: 'src/moved.js', to: 'src/renamed.js' },
    { write: 'src/clean.js', content: UNREACHABLE },
  ],
}
